config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/", to: "posts#index"
  resources :users, only: [:show, :destroy]
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :pic
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
      if @post.save
    redirect_to @post
    flash[:notice]  = "post created!"
      else
    redirect_back(fallback_location: root_path)
    flash[:alert] = "post creation failed!"
      end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
	   post = Post.find(params[:id])
     if current_user == post.user
       post.destroy
     redirect_to "/posts"
     flash[:notice] = "Post destroyed"
    else
      redirect_back(fallback_location: root_path)
      flash[:notice] = "not authorised to delete post"
    end
  end
  def edit
    @post = Post.find(params[:id])
    if current_user != @post.user
      sign_out current_user
      redirect_to(root_path)
      flash[:notice] = "Unauthorized request"
    end
  end
  def update
      @post = Post.find(params[:id])
      if current_user == @post.user
        @post.update(post_params)
      redirect_to @post
      flash[:notice] = "Post updated"
     else
       redirect_back(fallback_location: root_path)
       flash[:notice] = "not authorised to edit post"
     end
  end

  private
  def post_params
    params.require(:post).permit(:caption, :pic, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light ">
  <a class="navbar-brand" href="<%="/posts"%>">insta:blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">




    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <% if user_signed_in? %>
      <div class="margin-left">logged in as <strong><%= current_user.email %></strong></div>
      <a class="nav-link" href="<%=edit_user_registration_path%>">edit profile</a>
      <%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
    <a class="nav-link" href="<%="/posts"%>">home</a>
  <a class="nav-link" href="/posts/new">new</a>
    <% else %>
    <a class="nav-link" href="<%=new_user_registration_path%>">Sign up</a>
<a class="nav-link" href="<%=new_user_session_path%>">Login</a>

    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>instablog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
  image: <%= image_tag @post.pic.variant(auto_orient: true), class: "my-pic" %>
  <%= form_with model: @post do |f| %>
  <div>caption: <%= f.text_area :caption, required: true %></div>
  <%= f.submit %>
  <% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-auto">
        <h1 class="title">home</h1>
        <% @posts.each do |post| %>
          <div class="card" style="width:18rem;">
            <%= link_to(image_tag(post.pic.variant(auto_orient: true), class: "my-pic"), post) %>
            <div class="card-body">
              <p class="card-text"><%= post.caption %></p>
              <p class="card-text">author: <%= link_to post.user.email, post.user %></p>
              <p class="card-text">created: <%= post.created_at.strftime("%B %d %Y") %></p>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post do |f| %>
  image: <%= f.file_field :pic %>
  <div>caption: <%= f.text_area :caption, required: true %></div>
  <div>content: <%= f.text_area :content, required: true %></div>
  <%= f.submit %>
  <% end %>

app/views/posts/show.html.erb
<%= image_tag @post.pic.variant(auto_orient: true), class: "my-pic" %>
<p class="caption"><%= @post.caption %></p>
<p class="date">author: <%= link_to @post.user.email, @post.user %></p>
<p class="date">created: <%= @post.created_at.strftime("%B %d %Y") %></p>
<div class="content"><%= @post.content %></div>
<% if current_user == @post.user %>
<div class=btn><%= button_to "Delete", @post, method: :delete,data: {confirm: "Are you sure?"}%></div>
<div class=btn><%= button_to "Update",edit_post_path, method: :get %></div>
<%end%>

app/views/users/show.html.erb
<p> profile : <%= @user.email %></p>

<% @user.posts.each do |post| %>
<%= link_to(image_tag(post.pic, class: "my-pic"), post) %>
<p><%= post.caption %></p>

<% end %>